language: java
jdk:
  - openjdk11

before_install:
  - chmod +x mvnw

script:
  - ./mvnw clean test jacoco:report

after_success:
  - ./mvnw coveralls:report

env:
  global:
    - secure: "laNCEyZUpkDsdVjjscLsRRl3S0oZF4BOC"

# Caching settings to speed up the build
cache:
  directories:
    - $HOME/.m2
